stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  pre_preprocessing:
    cmd: python src/data/data_prep.py
    deps:
    - data/raw
    - src/data/data_prep.py
    outs:
    - data/processed
  model_buliding:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/model2.pkl
  # model_evaluation:
  #   cmd: python src/model/model_evaluation.py
  #   deps:
  #   - models/model2.pkl
  #   - src/model/model_evaluation.py
  #   metrics:
  #   - reports/metrics.json
  # model_evaluation:
  #   cmd: python src/model/model_evaluation.py
  #   deps:
  #   - models/model2.pkl
  #   - src/model/model_evaluation.py
  #   metrics:
  #   - reports/metrics.json
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model2.pkl
    - src/model/model_evaluation.py
    metrics:
    - metrics.json
